root = "."
tmp_dir = "tmp"

[build]
cmd = "go build -o tmp/api ./cmd/api"
bin = "tmp/api"
include_ext = ["go"]
include_dir = ["cmd/api", "internal", "pkg"]
exclude_dir = ["tmp", "node_modules", "cmd/cli", "cmd/web", "cmd/core", "cmd/distribution"]
kill_delay = "200ms"
poll = true
poll_interval = 500

[log]
time = false
