app: nvoi
env: production

providers:
  compute: hetzner
  dns: cloudflare
  storage: cloudflare
  build: local
  secrets: infisical

servers:
  master:
    type: cax11
    region: nbg1
    role: master

firewall: default

storage:
  releases: {}

build:
  distribution: ./cmd/distribution

services:
  distribution:
    build: distribution
    port: 3001
    storage:
      - releases

domains:
  distribution: [get.nvoi.to]
