package api

import (
	"encoding/json"
	"os"
	"strings"
	"testing"

	"gorm.io/gorm"
)

func init() {
	os.Setenv("ENCRYPTION_KEY", "0123456789abcdef0123456789abcdef0123456789abcdef0123456789abcdef")
	_ = InitEncryption()
}

func TestComputeProvider_Valid(t *testing.T) {
	valid := []ComputeProvider{ComputeHetzner, ComputeAWS, ComputeScaleway}
	for _, p := range valid {
		if !p.Valid() {
			t.Errorf("%q should be valid", p)
		}
	}
	if ComputeProvider("digitalocean").Valid() {
		t.Error("digitalocean should not be valid")
	}
	if ComputeProvider("").Valid() {
		t.Error("empty should not be valid")
	}
}

func TestDNSProvider_Valid(t *testing.T) {
	valid := []DNSProvider{DNSCloudflare, DNSAWS}
	for _, p := range valid {
		if !p.Valid() {
			t.Errorf("%q should be valid", p)
		}
	}
	if DNSProvider("godaddy").Valid() {
		t.Error("godaddy should not be valid")
	}
}

func TestStorageProvider_Valid(t *testing.T) {
	valid := []StorageProvider{StorageCloudflare, StorageAWS}
	for _, p := range valid {
		if !p.Valid() {
			t.Errorf("%q should be valid", p)
		}
	}
	if StorageProvider("gcs").Valid() {
		t.Error("gcs should not be valid")
	}
}

func TestBuildProvider_Valid(t *testing.T) {
	valid := []BuildProvider{BuildLocal, BuildDaytona, BuildGitHub}
	for _, p := range valid {
		if !validBuildProviders[p] {
			t.Errorf("%q should be valid", p)
		}
	}
	if validBuildProviders[BuildProvider("circleci")] {
		t.Error("circleci should not be valid")
	}
}

func TestRepoConfig_ValidateProviders(t *testing.T) {
	// Valid: all set.
	rc := &RepoConfig{
		ComputeProvider: ComputeHetzner,
		DNSProvider:     DNSCloudflare,
		StorageProvider: StorageAWS,
		BuildProvider:   BuildDaytona,
	}
	if err := rc.ValidateProviders(); err != nil {
		t.Errorf("all valid: %v", err)
	}

	// Valid: only compute (others optional).
	rc = &RepoConfig{ComputeProvider: ComputeAWS}
	if err := rc.ValidateProviders(); err != nil {
		t.Errorf("compute only: %v", err)
	}

	// Invalid compute.
	rc = &RepoConfig{ComputeProvider: "nope"}
	if err := rc.ValidateProviders(); err == nil {
		t.Error("expected error for invalid compute provider")
	}

	// Invalid DNS.
	rc = &RepoConfig{ComputeProvider: ComputeHetzner, DNSProvider: "nope"}
	if err := rc.ValidateProviders(); err == nil {
		t.Error("expected error for invalid dns provider")
	}

	// Invalid storage.
	rc = &RepoConfig{ComputeProvider: ComputeHetzner, StorageProvider: "nope"}
	if err := rc.ValidateProviders(); err == nil {
		t.Error("expected error for invalid storage provider")
	}

	// Invalid build.
	rc = &RepoConfig{ComputeProvider: ComputeHetzner, BuildProvider: "nope"}
	if err := rc.ValidateProviders(); err == nil {
		t.Error("expected error for invalid build provider")
	}
}

func TestDeployment_Lifecycle(t *testing.T) {
	db := TestDB()

	// Create supporting records.
	user := User{GithubUsername: "test", GithubToken: "ghp_test"}
	db.Create(&user)
	ws := Workspace{Name: "default", CreatedBy: user.ID}
	db.Create(&ws)
	db.Create(&WorkspaceUser{UserID: user.ID, WorkspaceID: ws.ID, Role: "owner"})
	repo := Repo{WorkspaceID: ws.ID, Name: "app"}
	db.Create(&repo)
	rc := RepoConfig{RepoID: repo.ID, Version: 1, ComputeProvider: ComputeHetzner, Config: "servers: {}"}
	db.Create(&rc)

	// Create deployment.
	deploy := Deployment{RepoID: repo.ID, RepoConfigID: rc.ID}
	if err := db.Create(&deploy).Error; err != nil {
		t.Fatalf("create deployment: %v", err)
	}
	if deploy.ID == "" {
		t.Error("deployment ID should be set")
	}
	if deploy.Status != DeploymentPending {
		t.Errorf("status = %q, want pending", deploy.Status)
	}

	// Add steps.
	step1 := DeploymentStep{DeploymentID: deploy.ID, Position: 1, Kind: "instance.set", Name: "master", Params: `{"type":"cx23"}`}
	step2 := DeploymentStep{DeploymentID: deploy.ID, Position: 2, Kind: "service.set", Name: "web", Params: `{"image":"nginx"}`}
	db.Create(&step1)
	db.Create(&step2)

	// Add log to step1.
	log := DeploymentStepLog{DeploymentStepID: step1.ID, Line: `{"type":"progress","message":"waiting for SSH"}`}
	db.Create(&log)

	// Load deployment with steps and logs.
	var loaded Deployment
	db.Preload("Steps", func(db *gorm.DB) *gorm.DB {
		return db.Order("position")
	}).Preload("Steps.Logs").First(&loaded, "id = ?", deploy.ID)

	if len(loaded.Steps) != 2 {
		t.Fatalf("steps = %d, want 2", len(loaded.Steps))
	}
	if loaded.Steps[0].Kind != "instance.set" {
		t.Errorf("step[0].kind = %q", loaded.Steps[0].Kind)
	}
	if loaded.Steps[1].Kind != "service.set" {
		t.Errorf("step[1].kind = %q", loaded.Steps[1].Kind)
	}
	if len(loaded.Steps[0].Logs) != 1 {
		t.Fatalf("step[0].logs = %d, want 1", len(loaded.Steps[0].Logs))
	}
	if loaded.Steps[0].Logs[0].Line != `{"type":"progress","message":"waiting for SSH"}` {
		t.Errorf("log line = %q", loaded.Steps[0].Logs[0].Line)
	}
}

func TestRepo_SSHKeysAutoGenerated(t *testing.T) {
	db := TestDB()

	user := User{GithubUsername: "test", GithubToken: "ghp_test"}
	db.Create(&user)
	ws := Workspace{Name: "default", CreatedBy: user.ID}
	db.Create(&ws)
	db.Create(&WorkspaceUser{UserID: user.ID, WorkspaceID: ws.ID, Role: "owner"})

	repo := Repo{WorkspaceID: ws.ID, Name: "app"}
	if err := db.Create(&repo).Error; err != nil {
		t.Fatalf("create repo: %v", err)
	}

	// Reload to trigger AfterFind (decrypt).
	var loaded Repo
	db.First(&loaded, "id = ?", repo.ID)

	if loaded.SSHPrivateKey == "" {
		t.Error("SSHPrivateKey should be auto-generated, got empty")
	}
	if loaded.SSHPublicKey == "" {
		t.Error("SSHPublicKey should be auto-generated, got empty")
	}
	if loaded.SSHPrivateKey[:5] != "-----" {
		t.Errorf("SSHPrivateKey should be PEM, got %q...", loaded.SSHPrivateKey[:20])
	}
	if loaded.SSHPublicKey[:4] != "ssh-" {
		t.Errorf("SSHPublicKey should start with ssh-, got %q...", loaded.SSHPublicKey[:20])
	}
}

func TestRepo_EnvironmentDefaultsToProduction(t *testing.T) {
	db := TestDB()

	user := User{GithubUsername: "test", GithubToken: "ghp_test"}
	db.Create(&user)
	ws := Workspace{Name: "default", CreatedBy: user.ID}
	db.Create(&ws)
	db.Create(&WorkspaceUser{UserID: user.ID, WorkspaceID: ws.ID, Role: "owner"})

	// Create without setting Environment.
	repo := Repo{WorkspaceID: ws.ID, Name: "app"}
	db.Create(&repo)

	var loaded Repo
	db.First(&loaded, "id = ?", repo.ID)

	if loaded.Environment != "production" {
		t.Errorf("Environment = %q, want production", loaded.Environment)
	}
}

func TestRepo_EnvironmentCanBeSet(t *testing.T) {
	db := TestDB()

	user := User{GithubUsername: "test", GithubToken: "ghp_test"}
	db.Create(&user)
	ws := Workspace{Name: "default", CreatedBy: user.ID}
	db.Create(&ws)
	db.Create(&WorkspaceUser{UserID: user.ID, WorkspaceID: ws.ID, Role: "owner"})

	repo := Repo{WorkspaceID: ws.ID, Name: "app", Environment: "staging"}
	db.Create(&repo)

	var loaded Repo
	db.First(&loaded, "id = ?", repo.ID)

	if loaded.Environment != "staging" {
		t.Errorf("Environment = %q, want staging", loaded.Environment)
	}
}

func TestUser_GithubTokenEncryptedAtRest(t *testing.T) {
	db := TestDB()

	user := User{GithubUsername: "tokenuser", GithubToken: "ghp_abc123secret"}
	if err := db.Create(&user).Error; err != nil {
		t.Fatalf("create user: %v", err)
	}

	// Raw DB value should be encrypted (not the original token).
	var raw struct{ GithubToken string }
	db.Raw("SELECT github_token FROM users WHERE id = ?", user.ID).Scan(&raw)
	if raw.GithubToken == "ghp_abc123secret" {
		t.Error("token should be encrypted at rest, got raw value")
	}
	if raw.GithubToken == "" {
		t.Error("token should not be empty")
	}

	// Load via GORM — AfterFind decrypts.
	var loaded User
	db.First(&loaded, "id = ?", user.ID)
	if loaded.GithubToken != "ghp_abc123secret" {
		t.Errorf("decrypted token = %q, want ghp_abc123secret", loaded.GithubToken)
	}
}

func TestUser_GithubTokenNotInJSON(t *testing.T) {
	// GithubToken has json:"-" — should never appear in JSON serialization.
	user := User{GithubUsername: "hidden", GithubToken: "ghp_secret"}
	data, _ := json.Marshal(user)
	if strings.Contains(string(data), "ghp_secret") {
		t.Errorf("GithubToken should not appear in JSON: %s", string(data))
	}
	if strings.Contains(string(data), "github_token") {
		t.Errorf("github_token key should not appear in JSON: %s", string(data))
	}
}

func TestUser_GithubTokenUpdatedOnRelogin(t *testing.T) {
	db := TestDB()

	user := User{GithubUsername: "updater", GithubToken: "ghp_old_token"}
	db.Create(&user)

	// Simulate re-login: update token.
	user.GithubToken = "ghp_new_token"
	db.Save(&user)

	var loaded User
	db.First(&loaded, "id = ?", user.ID)
	if loaded.GithubToken != "ghp_new_token" {
		t.Errorf("token after update = %q, want ghp_new_token", loaded.GithubToken)
	}
}
