package api

import (
	"encoding/json"
	"os"
	"strings"
	"testing"
)

// ── Agent token tests ──────────────────────────────────────────────────────

func TestRepo_AgentTokenAutoGenerated(t *testing.T) {
	db := TestDB()

	user := User{GithubUsername: "test-agent", GithubToken: "ghp_test"}
	db.Create(&user)
	ws := Workspace{Name: "default", CreatedBy: user.ID}
	db.Create(&ws)

	repo := Repo{WorkspaceID: ws.ID, Name: "app"}
	if err := db.Create(&repo).Error; err != nil {
		t.Fatalf("create repo: %v", err)
	}

	if repo.AgentToken == "" {
		t.Error("AgentToken should be auto-generated at creation")
	}
	if len(repo.AgentToken) != 64 { // 32 bytes hex-encoded
		t.Errorf("AgentToken length = %d, want 64 hex chars", len(repo.AgentToken))
	}
	if repo.AgentTokenHash == "" {
		t.Error("AgentTokenHash should be set at creation")
	}
}

func TestRepo_AgentTokenNotInJSON(t *testing.T) {
	repo := Repo{AgentToken: "secret-token-value", AgentTokenHash: "somehash"}
	data, _ := json.Marshal(repo)
	if strings.Contains(string(data), "secret-token-value") {
		t.Error("AgentToken should not appear in JSON")
	}
	if strings.Contains(string(data), "somehash") {
		t.Error("AgentTokenHash should not appear in JSON")
	}
}

func TestValidateAgentToken_CorrectToken(t *testing.T) {
	token := "abc123"
	hash := hashToken(token)
	if !ValidateAgentToken(token, hash) {
		t.Error("correct token should validate")
	}
}

func TestValidateAgentToken_WrongToken(t *testing.T) {
	hash := hashToken("correct")
	if ValidateAgentToken("wrong", hash) {
		t.Error("wrong token should not validate")
	}
}

func TestValidateAgentToken_EmptyHash(t *testing.T) {
	if ValidateAgentToken("anything", "") {
		t.Error("empty hash should never validate")
	}
}

func TestValidateAgentToken_EmptyToken(t *testing.T) {
	hash := hashToken("real")
	if ValidateAgentToken("", hash) {
		t.Error("empty token should not validate")
	}
}

func TestRepo_AgentTokenValidatesViaHash(t *testing.T) {
	db := TestDB()

	user := User{GithubUsername: "test-validate", GithubToken: "ghp_test"}
	db.Create(&user)
	ws := Workspace{Name: "default", CreatedBy: user.ID}
	db.Create(&ws)

	repo := Repo{WorkspaceID: ws.ID, Name: "myapp", Environment: "prod"}
	db.Create(&repo)

	// The plaintext token validates against the stored hash.
	if !ValidateAgentToken(repo.AgentToken, repo.AgentTokenHash) {
		t.Error("freshly created repo token should validate against its own hash")
	}

	// A different token does not validate.
	if ValidateAgentToken("wrong-token", repo.AgentTokenHash) {
		t.Error("wrong token should not validate")
	}
}

func init() {
	os.Setenv("ENCRYPTION_KEY", "0123456789abcdef0123456789abcdef0123456789abcdef0123456789abcdef")
	_ = InitEncryption()
}

func TestRepo_SSHKeysAutoGenerated(t *testing.T) {
	db := TestDB()

	user := User{GithubUsername: "test", GithubToken: "ghp_test"}
	db.Create(&user)
	ws := Workspace{Name: "default", CreatedBy: user.ID}
	db.Create(&ws)
	db.Create(&WorkspaceUser{UserID: user.ID, WorkspaceID: ws.ID, Role: "owner"})

	repo := Repo{WorkspaceID: ws.ID, Name: "app"}
	if err := db.Create(&repo).Error; err != nil {
		t.Fatalf("create repo: %v", err)
	}

	// Reload to trigger AfterFind (decrypt).
	var loaded Repo
	db.First(&loaded, "id = ?", repo.ID)

	if loaded.SSHPrivateKey == "" {
		t.Error("SSHPrivateKey should be auto-generated, got empty")
	}
	if loaded.SSHPublicKey == "" {
		t.Error("SSHPublicKey should be auto-generated, got empty")
	}
	if loaded.SSHPrivateKey[:5] != "-----" {
		t.Errorf("SSHPrivateKey should be PEM, got %q...", loaded.SSHPrivateKey[:20])
	}
	if loaded.SSHPublicKey[:4] != "ssh-" {
		t.Errorf("SSHPublicKey should start with ssh-, got %q...", loaded.SSHPublicKey[:20])
	}
}

func TestRepo_EnvironmentDefaultsToProduction(t *testing.T) {
	db := TestDB()

	user := User{GithubUsername: "test", GithubToken: "ghp_test"}
	db.Create(&user)
	ws := Workspace{Name: "default", CreatedBy: user.ID}
	db.Create(&ws)
	db.Create(&WorkspaceUser{UserID: user.ID, WorkspaceID: ws.ID, Role: "owner"})

	repo := Repo{WorkspaceID: ws.ID, Name: "app"}
	db.Create(&repo)

	var loaded Repo
	db.First(&loaded, "id = ?", repo.ID)

	if loaded.Environment != "production" {
		t.Errorf("Environment = %q, want production", loaded.Environment)
	}
}

func TestRepo_EnvironmentCanBeSet(t *testing.T) {
	db := TestDB()

	user := User{GithubUsername: "test", GithubToken: "ghp_test"}
	db.Create(&user)
	ws := Workspace{Name: "default", CreatedBy: user.ID}
	db.Create(&ws)
	db.Create(&WorkspaceUser{UserID: user.ID, WorkspaceID: ws.ID, Role: "owner"})

	repo := Repo{WorkspaceID: ws.ID, Name: "app", Environment: "staging"}
	db.Create(&repo)

	var loaded Repo
	db.First(&loaded, "id = ?", repo.ID)

	if loaded.Environment != "staging" {
		t.Errorf("Environment = %q, want staging", loaded.Environment)
	}
}

func TestUser_GithubTokenEncryptedAtRest(t *testing.T) {
	db := TestDB()

	user := User{GithubUsername: "tokenuser", GithubToken: "ghp_abc123secret"}
	if err := db.Create(&user).Error; err != nil {
		t.Fatalf("create user: %v", err)
	}

	var raw struct{ GithubToken string }
	db.Raw("SELECT github_token FROM users WHERE id = ?", user.ID).Scan(&raw)
	if raw.GithubToken == "ghp_abc123secret" {
		t.Error("token should be encrypted at rest, got raw value")
	}
	if raw.GithubToken == "" {
		t.Error("token should not be empty")
	}

	var loaded User
	db.First(&loaded, "id = ?", user.ID)
	if loaded.GithubToken != "ghp_abc123secret" {
		t.Errorf("decrypted token = %q, want ghp_abc123secret", loaded.GithubToken)
	}
}

func TestUser_GithubTokenNotInJSON(t *testing.T) {
	user := User{GithubUsername: "hidden", GithubToken: "ghp_secret"}
	data, _ := json.Marshal(user)
	if strings.Contains(string(data), "ghp_secret") {
		t.Errorf("GithubToken should not appear in JSON: %s", string(data))
	}
	if strings.Contains(string(data), "github_token") {
		t.Errorf("github_token key should not appear in JSON: %s", string(data))
	}
}

func TestUser_GithubTokenUpdatedOnRelogin(t *testing.T) {
	db := TestDB()

	user := User{GithubUsername: "updater", GithubToken: "ghp_old_token"}
	db.Create(&user)

	user.GithubToken = "ghp_new_token"
	db.Save(&user)

	var loaded User
	db.First(&loaded, "id = ?", user.ID)
	if loaded.GithubToken != "ghp_new_token" {
		t.Errorf("token after update = %q, want ghp_new_token", loaded.GithubToken)
	}
}

func TestCommandLog_Lifecycle(t *testing.T) {
	db := TestDB()

	user := User{GithubUsername: "test", GithubToken: "ghp_test"}
	db.Create(&user)
	ws := Workspace{Name: "default", CreatedBy: user.ID}
	db.Create(&ws)
	db.Create(&WorkspaceUser{UserID: user.ID, WorkspaceID: ws.ID, Role: "owner"})
	repo := Repo{WorkspaceID: ws.ID, Name: "app"}
	db.Create(&repo)

	cl := CommandLog{
		RepoID:     repo.ID,
		UserID:     user.ID,
		Kind:       "instance.set",
		Name:       "master",
		Status:     "succeeded",
		DurationMs: 4500,
	}
	if err := db.Create(&cl).Error; err != nil {
		t.Fatalf("create command log: %v", err)
	}
	if cl.ID == "" {
		t.Error("command log ID should be set")
	}

	var loaded CommandLog
	db.First(&loaded, "id = ?", cl.ID)
	if loaded.Kind != "instance.set" {
		t.Errorf("kind = %q, want instance.set", loaded.Kind)
	}
	if loaded.DurationMs != 4500 {
		t.Errorf("duration = %d, want 4500", loaded.DurationMs)
	}
}
